language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "devops-kf"
    token:
      secure: "ieMYIo1Dm3VNUNeaVsLiZtRuOEOruL77RUTG54/0o5rMJy0x1pMfoW9zdAKSOQaKxFg97AjkxIZZWRc8e/GlDkctBa7h91r2J0GHOSFlBxHHQgFLrnNQq8rIzosnLYTzh1hf7xIP41uVtFOo5ewX9agcs8PWGi3kkJCE8jFO4X6Nt0S5FQi12d9kdnY52pI7SaTlXXNwicr9B9C5jMAZBX0f93GjZd2iidMMegG4GbixdUcbYuqI8cO2T6dVfph0EMqeOTEAmq9cpgTqpvxTu1VXXORUUGBNrk2Qz/GOf1v+mgTWex1X0MuPcdoThIHEOAHWaPfhp07n6OMqGo9ALTfztzW4pX7+M2NDx4NXKleehKs7SHyGLttlw9SfoS//blG+5LEyM2p9Ptyhna6eZZYODLjQpDFk1JXhO1Mpfhn9LX/v8oZdQxk6qD3ei84STizkqfuF29YqvMdmjR92jqppYbCq0XDrvfLii6iBBuC7OS7N4FXES6mVI2sQGw8fJHFYTsSaPLCx0pEvC5UR6iFd1mJpkwbr63Q17mQk1UjVuJOd2JI/SjVsWQ3ksdnphr1Z4ohTQcFwwJeVxmyiX4rlp08pwKOeZvdeKUT56vI9YamsZPvbvTciveGraZwdbsLYBaBZKL3vTogNVRXr95gc7l3KcvjulAb/mugwTfE="
script:
  - pytest
  - sonar-scanner
branches:
  only:
    - main
    - development